# @format

BOT:
  OWNERS: ["1173547185758015498"]
  ADMINS: ["1173547185758015498"]

LINKS:
  SUPPORT: "https://discord.gg/DApdRsEFtb"
  MONGO_URI: "mongodb+srv://Kronix1:arjun@cluster0.ob9wwsc.mongodb.net/?retryWrites=true&w=majority"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "498f461b962443cfaf9539c610e2ea81"

MANAGER:
  OWNER: "1173547185758015498"
  TOKEN: ""

FUEGO:
  PREFIX: ","
  EMOJIS: "black"
  COLOR: "#555555"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: ""
  TOPGGAUTH: ""


WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1254308889906643084/BZp1u-ZUt5GkwgscIG_rT1Ss0ZmPBG2b0SvWSET_FaXfRVrA75BlTF4KtXOW1neFUri2"
  STATIC: "https://discord.com/api/webhooks/1254308889906643084/BZp1u-ZUt5GkwgscIG_rT1Ss0ZmPBG2b0SvWSET_FaXfRVrA75BlTF4KtXOW1neFUri2"
  PLAYER: "https://discord.com/api/webhooks/1254308889906643084/BZp1u-ZUt5GkwgscIG_rT1Ss0ZmPBG2b0SvWSET_FaXfRVrA75BlTF4KtXOW1neFUri2"
  SERVER: "https://discord.com/api/webhooks/1254308889906643084/BZp1u-ZUt5GkwgscIG_rT1Ss0ZmPBG2b0SvWSET_FaXfRVrA75BlTF4KtXOW1neFUri2"
  COMMAND: "https://discord.com/api/webhooks/1254308889906643084/BZp1u-ZUt5GkwgscIG_rT1Ss0ZmPBG2b0SvWSET_FaXfRVrA75BlTF4KtXOW1neFUri2"
