# @format

BOT:
  OWNERS: ["1131953433134497923"]
  ADMINS: ["1131953433134497923"]

LINKS:
  SUPPORT: "https://discord.gg/GPzYFx7zfe"
  MONGO_URI: "mongodb+srv://Kronix1:arjun@cluster0.ob9wwsc.mongodb.net/?retryWrites=true&w=majority"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "498f461b962443cfaf9539c610e2ea81"

MANAGER:
  OWNER: "1131953433134497923"
  TOKEN: ""

FUEGO:
  PREFIX: "#"
  EMOJIS: "black"
  COLOR: "#555555"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: ""
  TOPGGAUTH: ""


WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1242433499684671591/O8B17QhpgjzA2HKBzHlA0_zs6XomWOKcMqkvOmes763onzbUX3ynfiyvYrBg6AKMnXHx"
  STATIC: "https://discord.com/api/webhooks/1242433499684671591/O8B17QhpgjzA2HKBzHlA0_zs6XomWOKcMqkvOmes763onzbUX3ynfiyvYrBg6AKMnXHx"
  PLAYER: "https://discord.com/api/webhooks/1242433499684671591/O8B17QhpgjzA2HKBzHlA0_zs6XomWOKcMqkvOmes763onzbUX3ynfiyvYrBg6AKMnXHx"
  SERVER: "https://discord.com/api/webhooks/1242433499684671591/O8B17QhpgjzA2HKBzHlA0_zs6XomWOKcMqkvOmes763onzbUX3ynfiyvYrBg6AKMnXHx"
  COMMAND: "https://discord.com/api/webhooks/1242433499684671591/O8B17QhpgjzA2HKBzHlA0_zs6XomWOKcMqkvOmes763onzbUX3ynfiyvYrBg6AKMnXHx"
